refactor, add export functionality to valgrind
* overall:
  - refactor
  - $PAGER is used if set, otherwise 'less' is used
  - fix typos
* with_time:
  - rename first CSV field: 'datetime' => 'start_time'
* with_valgrind:
  - learns --export which exports HEAP SUMMARY and LEAK SUMMARY values
    as CSV
* history:
  - better usage with more examples
  - --max-count=0 will disable skipping of commits and build all of the
    given commit range(s)
  - learns --stdin to read a given set of commits (instead of ranges)
  - make MAX_COUNT default 16 (12 before) as values of 2^X makes more sense
  - commits of commit range are now sorted by topology, not by timestamp

diff --git a/perf/history b/perf/history
--- a/perf/history
+++ b/perf/history
@@ -3,16 +3,50 @@
 ##
 # defaults
 #
-MAX_COUNT="${MAX_COUNT:-12}" # number of commits
-METHOD="${METHOD:-time}"     # measurement method
+MAX_COUNT=16             # number of commits
+METHOD=time              # measurement method
+COMMITS_FROM_STDIN=false # whether to get commits to be built from STDIN
 
+# Shows usage in a pager.
 show_usage() {
-	cat <<EOF | less --quit-if-one-screen
+	cat <<EOF | ${PAGER:-less --quit-if-one-screen}
 SYNOPSIS
-	$0 [--method=METHOD] [--max-count=N] commit-ish...
+	(1) $0 [--method=METHOD] [--max-count=N] <commit>...
+	(2) $0 [--method=METHOD] --stdin
 
 The purpose of this script is to generate a history of performance measurement
 results across a given commit range.
+
+
+BUILD TIME
+----------
+By default, this utility works in bisect fashion and limits the number of
+commits to be built to save build time.
+
+As an example, instead of building (*) all commits of a given range,
+
+      ************************************************************************
+
+some are skipped (.) as shown here:
+
+      *......*........*........*........*.........*........*.........*.......*
+
+The others are skipped with the idea that the results can be interpolated.
+
+
+USAGE
+-----
+(1) The <commit> argument as it is understood by git-rev-list.
+    Useful for commit ranges.
+
+(2) Useful when a specific list of commits (not a range) should be measured or
+    other functionality of git-rev-list is needed.
+    Example:
+
+      git-rev-list --reverse master...feature1 -- only/here/ | $0 --stdin
+
+    This would otherwise be impossible without emulating more of git-rev-list's
+    functionality.
 
 
 ALGORITHM
@@ -54,17 +88,22 @@ FILES AND DIRECTORIES
 
 OPTIONS
 -------
-	-h --help		show this help and exit
-	-m --method=METHOD	(default: $METHOD) time, perf, valgrind, or massif
-	-n --max-count=N	(default: $MAX_COUNT) maximum # of commits to measure
+	-h --help            show this help and exit
+	-m --method=METHOD   (default: $METHOD) time, perf, valgrind, or massif
+	-n --max-count=N     (default: $MAX_COUNT) max. # of commits to measure,
+			     or 0 to build all commits
+	   --stdin           take commit list from STDIN, disable max. # commits
 
+If --stdin is not given, it makes sense to pass roughly a power
+of two to --max-count if you want the number of skipped, consecutive commits
+not to differ too much.
 
 For details about the performance measurement ("method") scripts, read the
 usage of the lower-level script(s):
 
 	`dirname $0`/with_* --help
 
-About commit-ish: Consult the manpage if unsure how to specify commit ranges:
+About <commit>...: Consult the manpage if unsure how to specify commit ranges:
 
 	man gitrevisions
 
@@ -88,7 +127,7 @@ EOF
 }
 
 # check and reorder arguments (options first, then arguments)
-set -- $(getopt --unquoted -o hm:n: -l help,method:,max-count: -- "$@")
+set -- $(getopt --unquoted -o hm:n: -l help,method:,max-count:,stdin -- "$@")
 while [ -n "$1" ]
 do
 	case "$1" in
@@ -98,11 +137,21 @@ do
 		;;
 	-n|--max-count)
 		MAX_COUNT="$2"
+		[ "$MAX_COUNT" = "0" ] && MAX_COUNT= # skip no commits
 		shift 2
 		;;
 	-m|--method)
 		METHOD="$2"
 		shift 2
+		;;
+	--stdin)
+		# option for git rev-list to avoid walking the history when
+		# given a list of commits (instead of a commit range)
+		COMMITS_FROM_STDIN=true
+
+		# disable maximum number of commits
+		MAX_COUNT=
+		shift
 		;;
 	--)
 		shift
@@ -137,31 +186,48 @@ if [ -z "$ALL_ARCHBITS" ]
 then
 	if uname -m | grep -q "x86_64"
 	then
-		export ALL_ARCHBITS="64"
+		ALL_ARCHBITS="64"
 	else
-		export ALL_ARCHBITS="32"
+		ALL_ARCHBITS="32"
 	fi
 fi
+export ALL_ARCHBITS
 
 ##
-# get set of commits
+# GET SET OF COMMITS
 #
 HISTORY_DIR="$(mktemp -d "history-`date +%Y%m%d`-XXXXXX")"
 echo "New history directory: $HISTORY_DIR" >&2
 COMMITS="$HISTORY_DIR/commits.txt"
-git rev-list --bisect-all --max-count $MAX_COUNT \
-	--pretty=format:"%H %at (%ar) by %an: %s"  "$@" | \
 
-# remove unwanted lines (not part of the specified format. git bug?) \
-grep -v '^commit ' | \
+if $COMMITS_FROM_STDIN
+then
+	# take list of commits from STDIN, just decorate them with additional
+	# information
+	git rev-list --stdin --no-walk > $COMMITS \
+		--pretty=format:"%h %at (%ar) by %an: %s"
 
-# sort by timestamp
-sort -nk2 > $COMMITS
+else
+	# determine list of commits based on the given commit ranges,
+	# in bisect fashion with possible limit
+	git rev-list --bisect-all ${MAX_COUNT:+--max-count=$MAX_COUNT} "$@" \
+
+	# cut away distance property, e.g. "ab4fcea7 (dist=3)" => "ab4fcea7"
+	grep -o '^[[:xdigit:]]\+' | \
+
+	# sort by topology, print older ones first, and decorate
+	git rev-list --stdin --topo-order --no-walk --reverse \
+		--pretty=format:"%h %at (%ar) by %an: %s" | \
+
+	# remove unwanted lines (not part of the specified format. git bug?)
+	# and redirect to file
+	grep -v '^commit ' > $COMMITS
+fi
 
 
 # print summary and get confirmation to proceed
 {
-	echo "These are the commits that to be built and measured:" >&2
+	echo "These are the commits to be built and measured:" >&2
 	echo
 	cat $COMMITS
 	echo "(`wc -l < $COMMITS` commits in total)"
@@ -174,8 +240,8 @@ sort -nk2 > $COMMITS
 	else
 		echo "\t\$TEST_NAMES=\"$TEST_NAMES\""
 	fi
-} | less --quit-if-one-screen
-printf "Press Enter to proceed, or ^C to cancel ..." >&2
+} | ${PAGER:-less --quit-if-one-screen}
+printf "Press Enter to proceed, or ^C to abort ..." >&2
 read confirmation
 [ -z "$confirmation" ] || exit 1
 
diff --git a/perf/with_massif b/perf/with_massif
--- a/perf/with_massif
+++ b/perf/with_massif
@@ -1,19 +1,49 @@
 #! /bin/sh
 . `dirname $0`/lib/measure_utils.sh
-. perf/lib/massif.sh
 which valgrind >/dev/null || { echo "No valgrind found." >&2; exit 1; }
 
-if [ -n "$DIFF_TEST" ]
-then
+# DIFF COMMAND
+print_diff_cmd() {
 	echo "git diff --no-index perf_results/massif/${DIFF_TEST}-32_${BUILDCFG}.massif perf_results/massif/${DIFF_TEST}-64_${BUILDCFG}.massif"
 	exit 0
-fi
+}
 
+# Measures performance of $TEST_NAMES using `valgrind --tool=massif`.
+#
+# Depends on:
+#   * measure_utils.sh
+#   * `valgrind --tool=massif`
+#   * $TEST_NAMES
+#   * $PERF_DIR
+#   * $ARCHBITS
+#
+# Honors:
+#   * $START_TIME
+measure_performance() {
+	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force
+	build `cat $TEST_NAMES`
+
+	##
+	# MEASUREMENT
+	#
+	progress "VALGRIND-MASSIF-BASED MEASUREMENT ..."
+	for TESTNAME in `cat $TEST_NAMES`
+	do
+		echo "#------------------------------------------------------------------------" >&2
+		echo "# Running test $TESTNAME ... ########################" >&2
+		RESULT=$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.massif
+        RUNPARAMS="-x valgrind -x '--tool=massif' -x '--time-unit=B' -x '--detailed-freq=1' -x '--massif-out-file=$RESULT'"
+		mkdir -p `dirname $RESULT`
+		( set -x; scons CXXFLAGS="-fPIC" $SCONSFLAGS --run-force --runparams="${RUNPARAMS} -- -all" $TESTNAME >$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
+	done
+}
+
+##
+# MAIN
+#
+
+[ -n "$DIFF_TEST" ] && { print_diff_cmd; exit; }
+
+BUILDCFG="optimized"
 get_confirmation
-
-for ARCHBITS in $ALL_ARCHBITS
-do
-	measure_with_massif
-done
-
-echo "# Performance measurement done. ################################" >&2
+measure_performance_for_selected_archbits
diff --git a/perf/with_perf b/perf/with_perf
--- a/perf/with_perf
+++ b/perf/with_perf
@@ -1,7 +1,36 @@
 #! /bin/sh
 . `dirname $0`/lib/measure_utils.sh
-. perf/lib/perf.sh
 which perf >/dev/null || { echo "No perf found." >&2; exit 1; }
+
+
+# Measures performance of $ALL_TESTS using `perf`.
+#
+# Depends on:
+#   * measure_utils.sh
+#   * `perf`
+#   * $TEST_NAMES
+#   * $PERF_DIR
+#   * $BUILDCFG
+#   * $ARCHBITS
+measure_performance() {
+	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force 
+	build `cat $TEST_NAMES`
+	warmup `cat $TEST_NAMES`
+
+	##
+	# MEASUREMENT
+	#
+	progress "PERF-BASED MEASUREMENT ..."
+	for TESTNAME in `cat $TEST_NAMES`
+	do
+		echo "#------------------------------------------------------------------------" >&2
+		echo "# Running test $TESTNAME ... ########################" >&2
+		RESULT=$PERF_DIR/perf/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.perf
+		mkdir -p `dirname $RESULT`
+		( set -x; scons $SCONSFLAGS --run-force --runparams="-x perf -x record -x -F99 -x -g -x '-o$RESULT' -- -all" $TESTNAME >$PERF_DIR/perf/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
+	done
+}
+
 BUILDCFG="optimized"
 
 # DIFF COMMAND
@@ -12,10 +41,4 @@ then
 fi
 
 get_confirmation
-
-for ARCHBITS in $ALL_ARCHBITS
-do
-	measure_with_perf
-done
-
-echo "# Performance measurement done. ################################" >&2
+measure_performance_for_selected_archbits
diff --git a/perf/with_time b/perf/with_time
--- a/perf/with_time
+++ b/perf/with_time
@@ -1,19 +1,15 @@
 #! /bin/sh
 . `dirname $0`/lib/measure_utils.sh
-. perf/lib/time.sh
-BUILDCFG="optimized"
 
 # DIFF COMMAND
-if [ -n "$DIFF_TEST" ] then
+print_diff_cmd() {
 	echo "git diff --no-index perf_results/time/${DIFF_TEST}-32_${BUILDCFG}.csv perf_results/time/${DIFF_TEST}-64_${BUILDCFG}.csv"
-	exit
-fi
+}
 
 # EXPORT
-if $EXPORT
-then
+export_as_csv() {
 	# print CSV header
-	echo "datetime,testname,archbits,buildcfg,method,user[s],system[s],real[s],cpu,maxres[KB],avgres[KB],avgunshared[KB],avgunsharedstack[KB],swaps"
+	echo "start_time,testname,archbits,buildcfg,method,user[s],system[s],real[s],cpu,maxres[KB],avgres[KB],avgunshared[KB],avgunsharedstack[KB],swaps"
 
 # Example:
 #	$ tail -2 perf_results/time/CoastStorageTest-64_debug.csv
@@ -26,23 +22,68 @@ then
 		# 	* testname
 		#	* archbits
 		# 	* buildcfg
-		# 	* datetime
+		# 	* start_time
 		eval $(basename -s .csv $file |\
 		sed -e 's/\(\w\+\)-\([[:digit:]]\+\)_\(\w\+\)/testname="\1" \
 			archbits="\2" buildcfg="\3"/')
-		datetime=`tail -2 $file | head -1 | cut -b3-`
+		start_time=`tail -2 $file | head -1 | sed -e 's/^# *//'`
 
 		# print CSV with additional values prepended
-		tail -1 $file | sed -e "s/^/$datetime,$testname,$archbits,$buildcfg,/"
+		tail -1 $file | sed -e "s/^/$start_time,$testname,$archbits,$buildcfg,/"
 	done
-	exit
-fi
+}
 
+# Measures performance of $TEST_NAMES using `time`.
+#
+# Depends on:
+#   * common.sh
+#   * `time`
+#   * $TEST_NAMES
+#   * $PERF_DIR
+#   * $BUILDCFG
+#   * $ARCHBITS
+#   * $NTIMES
+#
+# Honors:
+#   * $START_TIME
+#   * $TIMES
+measure_performance() {
+
+	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force 
+	TIMES=${TIMES:-20} # number of times to run each test
+
+	build `cat $TEST_NAMES`
+	warmup `cat $TEST_NAMES`
+
+	##
+	# MEASUREMENT
+	#
+	progress "TIME-BASED MEASUREMENT ..."
+	for TESTNAME in `cat $TEST_NAMES`
+	do
+		echo "#------------------------------------------------------------------------" >&2
+		echo "# Running test $TESTNAME ... ########################" >&2
+		TIME_RESULT=$PERF_DIR/time/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.csv
+		mkdir -p `dirname $TIME_RESULT`
+
+		# write CSV header if file doesn't exist yet
+		if [ ! -e $TIME_RESULT ];
+		then
+			echo "start_time,user[s],system[s],real[s],cpu,maxres[KB],avgres[KB],avgunshared[KB],avgunsharedstack[KB],swaps" > $TIME_RESULT
+		fi
+
+		# run test n times and log statistics
+		( set -x; scons $SCONSFLAGS --run-force --runparams="-x /usr/bin/time -x '-f' -x '$START_TIME,%U,%S,%e,%P,%M,%t,%D,%p,%W' -x '--output=$TIME_RESULT' -x '--append' -x $NTIMES -x $TIMES -- -all" $TESTNAME >$PERF_DIR/time/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
+	done
+}
+
+##
+# MAIN
+#
+
+[ -n "$DIFF_TEST" ] && { print_diff_cmd; exit; }
+$EXPORT && { export_as_csv; exit; }
+
+BUILDCFG="optimized"
 get_confirmation
-
-for ARCHBITS in $ALL_ARCHBITS
-do
-	measure_with_time
-done
-
-echo "# Performance measurement done. ################################" >&2
+measure_performance_for_selected_archbits
diff --git a/perf/with_valgrind b/perf/with_valgrind
--- a/perf/with_valgrind
+++ b/perf/with_valgrind
@@ -1,20 +1,20 @@
 #! /bin/sh
 . `dirname $0`/lib/measure_utils.sh
-. perf/lib/valgrind.sh
 which valgrind >/dev/null || { echo "No valgrind found." >&2; exit 1; }
 
-if [ -n "$DIFF_TEST" ]
-then
+# DIFF COMMAND
+print_diff_cmd() {
 	echo "git diff --no-index perf_results/valgrind/${DIFF_TEST}-32_${BUILDCFG}.valgrind perf_results/valgrind/${DIFF_TEST}-64_${BUILDCFG}.valgrind"
 	echo "memory summary: find valgrind/ -print -iname '*.valgrind' -exec sed -n '/HEAP SUMMARY/,/Checked/p' {} \;"
-	exit 0
-fi
+}
 
 # EXPORT
-if $EXPORT
-then
+export_as_csv() {
 	# print CSV header
-	echo "datetime,testname,archbits,buildcfg,method,X,Y"
+	printf "start_time,testname,archbits,buildcfg,method," # test info
+	printf "definitely_lost[B],indirectly_lost[B],possibly_lost[B],still_reachable[B],suppressed[B]," # leak summary
+	printf "in_use_at_exit[B],allocs,frees,allocated[B]\n" # heap summary
+
 
 # Example:
 # $ cat perf_results/valgrind/CoastEBCDICTest-64_debug.valgrind
@@ -35,29 +35,118 @@ then
 #
 # [...]
 
-	for file in $PERF_DIR/valgrind/*-*_*.csv
+	for file in $PERF_DIR/valgrind/*-*_*.valgrind
 	do
-		# extract and set variables:
+		# summary variables about whole test
+		summary=`dirname $file`/`basename -s .valgrind $file`.summary
+
+		# extract variables from filename:
 		# 	* testname
 		#	* archbits
 		# 	* buildcfg
-		# 	* datetime
-		eval $(basename -s .csv $file |\
-		sed -e 's/\(\w\+\)-\([[:digit:]]\+\)_\(\w\+\)/testname="\1" \
-			archbits="\2" buildcfg="\3"/')
-		datetime=`tail -2 $file | head -1 | cut -b3-`
+		basename $file | sed -e 's/\(\w\+\)-\([[:digit:]]\+\)_\(\w\+\)\.\w\+/testname=\1\narchbits=\2\nbuildcfg=\3/' > $summary
 
-		# print CSV with additional values prepended
-		tail -1 $file | sed -e "s/^/$datetime,$testname,$archbits,$buildcfg,/"
+		##
+		# extract HEAP SUMMARY and LEAK SUMMARY values
+		#
+		sed -ne < $file '
+		/LEAK SUMMARY:$/,/^==[[:digit:]]\+==\s*$/ {
+		  /LEAK SUMMARY/n
+		  s/^==[[:digit:]]\+==\s*//
+		  / bytes /!d
+		  s/\([[:alpha:]]\) \([[:alpha:]]\)/\1_\2/
+		  s/ bytes.*//
+		  s/[, ]//g
+		  s/:/=/p
+		}
+
+		/HEAP SUMMARY:$/,/^==[[:digit:]]\+==\s*$/ {
+		  /HEAP SUMMARY/n
+		  s/^==[[:digit:]]\+==\s*//
+		  s/,//g
+		  s/in use at exit: \([[:digit:]]\+\) bytes.*/in_use_at_exit=\1/p
+		  s/total heap usage: \([[:digit:]]\+\) allocs \([[:digit:]]\+\) frees \([[:digit:]]\+\) bytes allocated.*/allocs=\1\nfrees=\2\nallocated=\3/p
+		}' |\
+
+		# sanitize: only allow variable declarations to integers, and
+		# only lower case variable names
+		grep '^[[:lower:]_]\+=[[:digit:]]\+$' >> $summary
+
+		# Example of resulting summary file:
+		#
+		#testname=CoastFoundationPerfTest
+		#archbits=64
+		#buildcfg=debug
+		#in_use_at_exit=72704
+		#allocs=1825093
+		#frees=1825092
+		#allocated=2925949417
+		#definitely_lost=0
+		#indirectly_lost=0
+		#possibly_lost=0
+		#still_reachable=72704
+		#suppressed=0
+
+		# set summary variables
+		eval `cat $summary` 
+
+		# get start time from file
+		start_time="$(cat `dirname $file`/${testname}.start_time)"
+
+		##
+		# print CSV data
+		#
+		printf "$start_time,$testname,$archbits,"
+		printf "$buildcfg,$definitely_lost,$indirectly_lost,$possibly_lost,$still_reachable,$suppressed,"
+		printf "$in_use_at_exit,$allocs,$frees,$allocated\n"
 	done
 	exit
-fi
+}
 
+
+# Measures performance of $TEST_NAMES using `valgrind`.
+#
+# Depends on:
+#   * measure_utils.sh
+#   * `valgrind`
+#   * $TEST_NAMES
+#   * $PERF_DIR
+#   * $BUILDCFG
+#   * $ARCHBITS
+#
+# Honors:
+#   * $START_TIME
+measure_performance() {
+	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force
+	build `cat $TEST_NAMES`
+	warmup `cat $TEST_NAMES`
+
+	##
+	# MEASUREMENT
+	#
+	progress "VALGRIND-BASED MEASUREMENT ..."
+	for TESTNAME in `cat $TEST_NAMES`
+	do
+		echo "#------------------------------------------------------------------------" >&2
+		echo "# Running test $TESTNAME ... ########################" >&2
+
+		# store start time which is the same for both 32/64 builds
+		echo "$START_TIME" > $PERF_DIR/valgrind/${TESTNAME}.start_time
+
+		RESULT=$PERF_DIR/valgrind/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.valgrind
+		mkdir -p `dirname $RESULT`
+		touch $RESULT # needed
+		( set -x; scons $SCONSFLAGS --run-force --runparams="-x valgrind -x '--leak-check=full' -x '--log-file=$RESULT' -x '--show-leak-kinds=all' -x -v -- -all" $TESTNAME >$PERF_DIR/valgrind/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
+	done
+}
+
+##
+# MAIN
+#
+
+[ -n "$DIFF_TEST" ] && { print_diff_cmd; exit; }
+$EXPORT && { export_as_csv; exit; }
+
+BUILDCFG="debug"
 get_confirmation
-
-for ARCHBITS in $ALL_ARCHBITS
-do
-	measure_with_valgrind
-done
-
-echo "# Performance measurement done. ################################" >&2
+measure_performance_for_selected_archbits
