Switched massif tests to optimized, removed useless warmup and added stack

diff --git a/perf/with_massif b/perf/with_massif
--- a/perf/with_massif
+++ b/perf/with_massif
@@ -13,10 +13,10 @@ get_confirmation
 
 for ARCHBITS in 64 32
 do
-	BUILDCFG="debug"
+	BUILDCFG="optimized"
 	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force
 	build `cat $ALL_TESTS`
-	warmup `cat $ALL_TESTS`
+#	warmup `cat $ALL_TESTS`
 
 	##
 	# MEASUREMENT
@@ -27,9 +27,9 @@ do
 		echo "#------------------------------------------------------------------------" >&2
 		echo "# Running test $TESTNAME ... ########################" >&2
 		RESULT=$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.massif
-        RUNPARAMS="-x valgrind -x '--tool=massif' -x '--time-unit=B' -x '--massif-out-file=$RESULT' -x '--stacks=yes'"
+        RUNPARAMS="-x valgrind -x '--tool=massif' -x '--time-unit=B' -x '--detailed-freq=1' -x '--massif-out-file=$RESULT'"
 		mkdir -p `dirname $RESULT`
-		( set -x; scons $SCONSFLAGS --run-force --runparams="${RUNPARAMS} -- -all" $TESTNAME >$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
+		( set -x; scons CXXFLAGS="-fPIC" $SCONSFLAGS --run-force --runparams="${RUNPARAMS} -- -all" $TESTNAME >$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
 	done
 done
 
